export const menuItemList = [
  /*{
    id: 1,
    title: "ASIDE.MENU.DASHBOARD.TITLE",
    name: "ASIDE.MENU.DASHBOARD.TITLE",
    route: "cm-dashboard",
    menuRoute: "cm-menu-company",
    apiPath: "dashboard",
    icon: "Chicken.svg",
  },*/
  {
    id: 2,
    title: "ASIDE.MENU.CREATE.CAMPAIGN.TITLE",
    name: "ASIDE.MENU.CREATE.CAMPAIGN.TITLE",
    route: "cm-campaign",
    menuRoute: "cm-campaign-menu",
    apiPath: "campaign",
    icon: "Pizza.svg",
  },
  {
    id: 3,
    title: "ASIDE.MENU.CAMPAIGN.LIST.TITLE",
    name: "ASIDE.MENU.CAMPAIGN.LIST.TITLE",
    route: "cm-campaigns",
    menuRoute: "cm-campaigns",
    apiPath: "campaigns",
    icon: "Fish.svg",
  },
  {
    id: 4,
    title: "ASIDE.MENU.CREATE.RULE.TITLE",
    name: "ASIDE.MENU.CREATE.RULE.TITLE",
    route: "cm-rule",
    menuRoute: "cm-rule-menu",
    apiPath: "rule",
    icon: "Cookie.svg",
  },
  {
    id: 5,
    title: "ASIDE.MENU.UPLOAD.CODE.TITLE",
    name: "ASIDE.MENU.UPLOAD.CODE.TITLE",
    route: "cm-code",
    menuRoute: "cm-code-menu",
    apiPath: "code",
    icon: "Pizza.svg",
  },
  {
    id: 6,
    title: "ASIDE.MENU.CONTACT.TITLE",
    name: "ASIDE.MENU.CONTACT.TITLE",
    route: "cm-contact",
    menuRoute: "cm-contact-menu",
    apiPath: "contact",
    icon: "Sushi.svg",
  },
  {
    id: 7,
    title: "ASIDE.MENU.CAMPAIGN.DASHBOARD.TITLE",
    name: "ASIDE.MENU.CAMPAIGN.DASHBOARD.TITLE",
    route: "cm-dashboard",
    menuRoute: "cm-dashboard-menu",
    apiPath: "dashboard",
    icon: "Sushi.svg",
  },
  {
    id: 8,
    title: "ASIDE.MENU.POLICY.SALE.TITLE",
    name: "ASIDE.MENU.POLICY.SALE.TITLE",
    route: "cm-policy-sale",
    menuRoute: "cm-policy-sale-menu",
    apiPath: "policySale",
    icon: "Sushi.svg",
  },
  {
    id: 9,
    title: "ASIDE.MENU.ADMIN.TITLE",
    name: "ASIDE.MENU.ADMIN.TITLE",
    route: "cm-admin",
    menuRoute: "cm-admin-menu",
    apiPath: "admin",
    icon: "Sushi.svg",
  },
  {
    id: 10,
    title: "ASIDE.MENU.TASK.MANAGEMENT.TITLE",
    name: "ASIDE.MENU.TASK.MANAGEMENT",
    route: "cm-task-management",
    menuRoute: "cm-task-management-menu",
    apiPath: "task-management",
    icon: "Cookie.svg",
  }
];
